remove comments and change job name

diff --git a/.github/workflows/main-workflow.yml b/.github/workflows/main-workflow.yml
--- a/.github/workflows/main-workflow.yml
+++ b/.github/workflows/main-workflow.yml
@@ -1,32 +1,19 @@
-# This is a basic workflow to help you get started with Actions
-
 name: CI
 
-# Controls when the workflow will run
 on:
-  # Triggers the workflow on push or pull request events but only for the "dev" branch
   push:
     branches: [ "dev" ]
 
-  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
-  build:
-    # The type of runner that the job will run on
+   trufflehog-scan:
     runs-on: ubuntu-latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v4
         with:
           fetch-depth: 2 # only need the last 2 commits (including current commit) to scan diffs
-
-      - name: Starting Pipeline Message
-        run: echo Starting pipeline...
       
       - name: TruffleHog OSS (Secret Scanning)
         uses: trufflesecurity/trufflehog@v3.90.13
@@ -36,3 +23,8 @@ jobs:
           head: ${{ github.sha }}
           path: ./
           extra_args: --debug
+      - name: Check TruffleHog Results
+        if: steps.trufflehog.outcome == 'failure'
+        run: |
+          echo "Secrets detected by TruffleHog. Failing pipeline."
+          exit 1
